name: arabic_learning_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.8
  flutter_tts: ^3.8.3
  audioplayers: ^6.1.0
  url_launcher: ^6.3.1
  package_info_plus: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/data/
    - assets/audio/
    - assets/grammar/
  fonts:
    - family: ArabicDisplay
      fonts:
        - asset: assets/fonts/Katibeh-Regular.ttf
    - family: ArabicBody
      fonts:
        - asset: assets/fonts/NotoNaskhArabic-Regular.ttf
    - family: NotoNaskhArabic
      fonts:
        - asset: assets/fonts/NotoNaskhArabic-Regular.ttf
